builds:
  - main: ./cmd/f1go
    binary: f1go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format_overrides:
      - goos: windows
        format: zip

brews:
  - tap:
      owner: acifani
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/acifani/formula1-go
    description: Command-line application to show Formula1 schedules, standings, and results
    license: MIT
    test: |
      system "#{bin}/f1go", "version"